// frontend/components/Navbar.jsx
import Link from "next/link";
import { useContext } from "react";
import { AuthContext } from "../pages/_app";

export function Navbar() {
  const [{ id, firstname, lastname }] = useContext(AuthContext);

  return (
    <nav className="navbar navbar-expand-lg navbar-light bg-light">
      <div className="container-fluid">
        <Link href="/">
          <a className="navbar-brand">GoodFood</a>
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav me-auto mb-2 mb-lg-0">
            <li className="nav-item">
              <Link href="/">
                <a className="nav-link active" aria-current="page" href="#">
                  Accueil
                </a>
              </Link>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#">
                Lien
              </a>
            </li>
          </ul>

          {!id ? (
            <form className="d-flex">
              <Link href="/connexion">
                <a className="btn btn-primary">Connexion</a>
              </Link>
              <Link href="/inscription">
                <a className="btn btn-outline-primary">Inscription</a>
              </Link>
            </form>
          ) : (
            <Link href="/">
              <a href="#">
                {firstname} {lastname}
              </a>
            </Link>
          )}
        </div>
      </div>
    </nav>
  );
}

// frontend-admin/components/NavBar.vue
<template>
  <div>
    <b-navbar toggleable="lg" type="dark">
      <b-navbar-brand href="/">GoodFood BackOffice</b-navbar-brand>

      <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

      <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav>
          <b-nav-item :to="'/'">Accueil</b-nav-item>
          <b-nav-item :to="'/resto'">Resto</b-nav-item>
          <b-nav-item :to="'/offres'">Offres</b-nav-item>
          <b-nav-item :to="'/commercial'">Commercial</b-nav-item>
          <b-nav-item :to="'/utilisateurs'">Utilisateurs</b-nav-item>
        </b-navbar-nav>

        <!-- Right aligned nav items -->
        <b-navbar-nav class="ml-auto">
          <div v-if="isUserLoggedIn">
            <p v-if="isUserLoggedIn">
              Bonjour, {{ user.firstname }} {{ user.lastname }}
            </p>
          <div v-if="!isUserLoggedIn">
            <b-button :to="'/login'">Connexion</b-button>
          </div>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>
  </div>
</template>

<script>
export default {
  data() {
    return {
      isUserLoggedIn: this.$auth.loggedIn,
      user: this.$auth.user,
    }
  },
  methods: {
    logOut() {
      this.$auth.logout()
    },
  },
}
</script>
